Add SAML addon.
friendica/friendica-addons pull request #1111
Opened 2021-05-17 04:18 UTC by very-ape

I'm running a set of services for friends and family and using Keycloak for account management. All of the services I run use SAML to create a smooth, integrated experience via single sign-on and single logout.

This addon replaces the signup and login mechanisms with automatic SAML SSO (and SLO).

2021-05-17 14:25 UTC, MrPetovan requested changes

2021-05-17 14:25 UTC, MrPetovan commented on saml/saml.php
> +    Hook::register('footer', 'addon/saml/saml.php', 'saml_footer');
Portability: This code is correct, but we've started using `__FILE__` instead to improve code reuse between addons and prevent rare issues with moved files.
```suggestion
    Hook::register('login_hook', __FILE__, 'saml_sso_initiate');
    Hook::register('logging_out', __FILE__, 'saml_slo_initiate');
    Hook::register('head', __FILE__, 'saml_head');
    Hook::register('footer', __FILE__, 'saml_footer');
```

2021-05-17 14:25 UTC, MrPetovan commented on saml/saml.php
> +            'A statement on the settings page explaining where the user should go to change their e-mail and password. HTML allowed.'
Please reconsider injecting a config value as a HTML string in the page. I would recommend enabling BBCode, the HMTL output is sanitized according to pretty strict standards. The method to convert BBCode to HTML is `\Friendica\Content\Text\BBCode::convert()`.

2021-05-17 14:25 UTC, MrPetovan commented on saml/saml.php
> +            DI::l10n()->t($description),
Unfortunately, these dynamic translation strings won't be picked up by our translation string collector script and as a result won't be available for our volunteer translators to translate in Transifex. You have to explicitly wrap each translation string with a `DI::l10n()->t()` call.

2021-05-17 14:25 UTC, MrPetovan commented on saml/saml.php
> +function saml_init($a) {
Code standards: We use a very slight variation of the PSR-2 coding standards that mandates a new line before function opening braces among other things, please check the rest of the basic rules: https://friendica.mrpetovan.com/help/Developers-Intro#Coding+standards

2021-05-17 14:25 UTC, MrPetovan commented on saml/saml.php
> +	Logger::error($e->getMessage());
Coding standards: Mixed indentation style, please use only tabs.

2021-05-17 14:25 UTC, MrPetovan commented on saml/saml.php
> +    if (!saml_is_configured()) return;
Coding standards: Please add braces to all conditions.

2021-05-17 14:25 UTC, MrPetovan commented on saml/templates/admin.tpl
> +-->
As a general rule, we don't include code comments in commits since we are using a versioning tool. Why does it need to be added to this file?

2021-05-17 18:14 UTC, very-ape commented
Thanks for the quick turnaround on that code review! I believe I've addressed all the problems you noted and have also added some friendly messages for when the addon triggers before it's configured.

2021-05-17 19:01 UTC, MrPetovan requested changes
Thank you for acting on the feedback, I have some more for you!

2021-05-17 19:01 UTC, MrPetovan commented on saml/saml.php
> +define("PW_LEN", 32); // number of characters to use for random passwords
Coding standards: Please use single quotes unless double quotes are needed for variable interpolation/special characters (like `\n`).

2021-05-17 19:01 UTC, MrPetovan commented on saml/saml.php
> +		true, // all the fields are required
Coding standards: Wrong indentation.

2021-05-17 19:01 UTC, MrPetovan commented on saml/saml.php
> +		$val = (!empty($_POST[$key]) ? Strings::escapeTags(trim($_POST[$key])) : '');
It used to be the norm, but `Strings::escapeTags` is now deprecated for processing user input. Instead, we rely on Smarty's default HTML escaping on display.

2021-05-17 19:01 UTC, MrPetovan commented on saml/saml.php
> +	// Not using safeset here since settings_statement is *meant* to include HTML tags.
With the switch to BBCode, this comment and the exception are now obsolete.

2021-05-17 19:01 UTC, MrPetovan commented on saml/saml.php
> +		'verified' => true
Coding standards: Wrong indentation.

2021-05-17 19:01 UTC, MrPetovan commented on saml/saml.php
> +	   'signMetadata' => true,
Coding standards: Wrong indentation.

2021-05-17 19:01 UTC, MrPetovan commented on saml/saml.php
> +	   /* Sign the Metadata */
Coding standards: Multi-line comment used for single-line comment.

2021-05-17 20:02 UTC, very-ape commented
Okay, I _think_ I got everything this time.

2021-05-17 21:20 UTC, MrPetovan approved these changes
Looks good to me, thanks!

2021-05-17 21:23 UTC, merged

2021-05-18 11:46 UTC, tobiasd commented
With #1113 merged, the translation of the SAML addon is now in the pipe for the translation teams