Add PHP-CS check
friendica/friendica-addons pull request #1123
Opened 2021-05-22 12:12 UTC by nupplaphil

2021-05-22 18:07 UTC, nupplaphil commented
https://github.com/friendica/friendica-addons/pull/1123/commits/622ec88fe302046de20f7eaeaa542aa1d6fbacd5 <-- with wrong PHP files included
https://github.com/friendica/friendica-addons/pull/1123/commits/95737984a0c2a482546063e3b63361ac97c1802e <-- wrong PHP files deleted :-)

I'm done! :-)

2021-05-22 21:17 UTC, MrPetovan requested changes
Let's spruce the step names a bit, shall we?

2021-05-22 21:17 UTC, MrPetovan commented on .drone.yml
> +  - name: clone friendica base
```suggestion
  - name: Clone friendica base
```

2021-05-22 21:17 UTC, MrPetovan commented on .drone.yml
> +  - name: clone friendica addon
```suggestion
  - name: Clone friendica addon
```

2021-05-23 11:37 UTC, MrPetovan approved these changes

2021-05-23 11:37 UTC, merged