Issue 10772: Avoid duplicated links to Twitter
friendica/friendica-addons pull request #1174
Opened 2021-09-27 20:30 UTC by annando

Fixes https://github.com/friendica/friendica/pull/10773

2021-09-27 21:43 UTC, MrPetovan requested changes

2021-09-27 21:43 UTC, MrPetovan commented on twitter/twitter.php
> +		if ((strpos($msg, $msgarr['url']) === false) && !empty($msgarr['url']) && (($msgarr['type'] != 'photo') || empty($msgarr['images']) || (count($msgarr['images']) > 4))) {
I would check if `$msgarr['url']` first before trying to find the URL in the message.
```suggestion
		if (!empty($msgarr['url']) && (strpos($msg, $msgarr['url']) === false) && (($msgarr['type'] != 'photo') || empty($msgarr['images']) || (count($msgarr['images']) > 4))) {
```

2021-09-28 03:21 UTC, annando commented on twitter/twitter.php
> +		if ((strpos($msg, $msgarr['url']) === false) && !empty($msgarr['url']) && (($msgarr['type'] != 'photo') || empty($msgarr['images']) || (count($msgarr['images']) > 4))) {
Details ;-)

2021-09-28 11:02 UTC, MrPetovan approved these changes

2021-09-28 11:02 UTC, merged