Add S3 Storage Backend
friendica/friendica-addons pull request #1236
Opened 2022-02-20 20:23 UTC by nupplaphil

Still WIP, but  think "almost" finished, details later :)

2022-02-25 00:44 UTC, MrPetovan requested changes

2022-02-25 00:44 UTC, MrPetovan commented on s3_storage/composer.json
> +    "akeeba/s3": "^2.0"
Code standards: Please normalize white space in the file.

2022-02-25 00:44 UTC, MrPetovan commented on s3_storage/tests/S3Test.php.bak
> +<?php
Is this file `.bak` meant to be committed?

2022-02-25 13:55 UTC, MrPetovan approved these changes

2022-02-25 13:55 UTC, MrPetovan commented on s3_storage/vendor/akeeba/s3/README.md
> +The most significant change in this version is that all methods use scalar type hints for parameters and return values. This _may_ break existing consumers which relied on implicit type conversion e.
Good news for these consumers, scalar type hints also do implicit conversion from strings to integers!

2022-02-25 13:55 UTC, MrPetovan commented on s3_storage/vendor/akeeba/s3/src/Acl.php
> +defined('AKEEBAENGINE') or die();
Huh? What's the point of this in all the files?

2022-02-25 13:56 UTC, merged

2022-02-25 14:20 UTC, AlfredSK commented
I'll check this out with my test node mordor.social and a Minio server. Thank you!

2022-02-25 15:04 UTC, nupplaphil commented
> I'll check this out with my test node mordor.social and a Minio server. Thank you!

I think you have to use v2/legacy flag, afaik

2022-02-26 01:33 UTC, MrPetovan commented on s3_storage/vendor/akeeba/s3/src/Configuration.php
> +		}
Why not 
```php
		} elseif (empty($this->getRegion())) {
			$this->setRegion('us-east-1');
		}
```