Introduce explicit HttpClient "Accept" parameter
friendica/friendica-addons pull request #1245
Opened 2022-04-02 19:21 UTC by nupplaphil

Part of https://github.com/friendica/friendica/pull/11389

2022-04-02 20:04 UTC, MrPetovan approved these changes

2022-04-02 21:13 UTC, annando requested changes
We should only use the `accept` header on `get` requests, since it isn't used for stuff like `post` and the other methods.

2022-04-02 21:13 UTC, annando commented on dwpost/dwpost.php
> +			$x = DI::httpClient()->post($dw_blog, $xml, HttpClientAccept::DEFAULT, ['Content-Type' => 'text/xml'])->getBody();
With a `post` we are transmitting the `content-type`, we aren't accepting stuff.

2022-04-02 21:13 UTC, annando commented on ijpost/ijpost.php
> +			$x = DI::httpClient()->post($ij_blog, $xml, HttpClientAccept::DEFAULT, ['Content-Type' => 'text/xml'])->getBody();
See above.

2022-04-02 21:13 UTC, annando commented on ljpost/ljpost.php
> +			$x = DI::httpClient()->post($lj_blog, $xml, HttpClientAccept::DEFAULT, ['Content-Type' => 'text/xml'])->getBody();
Same :-)

2022-04-02 21:13 UTC, annando commented on webdav_storage/src/WebDav.php
> +		return $this->client->request('mkcol', $uri, HttpClientAccept::DEFAULT, [HttpClientOptions::AUTH => $this->authOptions])
AFAIK the `mkcol` method isn't requesting data, so we shouldn't use that parameter there.

2022-04-02 21:13 UTC, annando commented on webdav_storage/src/WebDav.php
> +				$response = $this->client->request('delete', $checkUrl, HttpClientAccept::DEFAULT, [HttpClientOptions::AUTH => $this->authOptions]);
Same as above.

2022-04-02 21:13 UTC, annando commented on webdav_storage/src/WebDav.php
> +		$this->client->request('put', $this->url . '/' . $file[0], HttpClientAccept::DEFAULT, $opts);
Same :-)

2022-04-03 19:20 UTC, annando commented on webdav_storage/src/WebDav.php
> +use Friendica\Network\HTTPClient\Client\HttpClientAccept;
Is this line still needed?

2022-04-08 18:36 UTC, MrPetovan approved these changes

2022-04-08 18:36 UTC, merged