Audon Audio Chat based on the WebRTC Addon
friendica/friendica-addons pull request #1357
Opened 2023-06-18 09:45 UTC by loma-one

This Addon based on webrtc. Audon is a service of realtime audio chat.
With small changes, the WebRTC addon could be adapted to Audon so that it can be loaded into an iframe. In the ifram, the Friendica handle can be connected and a room opened. Audio conversations between Friendica users are possible.
The German language file was adapted. The other languages remained unchanged. I have left them in the data set because I do not know how to proceed with them.

2023-06-18 13:01 UTC, MrPetovan commented
For the langage files, please delete all the folders in `audo/lang` except the `audon/lang/C` folder. The `messages.po` in this folder will be loaded in Transifex to allow translators to work on their respective language, and then the language-specific folders will be created.

2023-06-18 13:08 UTC, MrPetovan requested changes

2023-06-18 13:08 UTC, MrPetovan commented on audon/audon.php
> +use Friendica\App;
From the code standards check:
```suggestion
```

2023-06-18 13:08 UTC, MrPetovan commented on audon/audon.php
> +}
```suggestion
function audon_install()
{
	Hook::register('app_menu', __FILE__, 'audon_app_menu');
}
```

2023-06-18 13:08 UTC, MrPetovan commented on audon/audon.php
> +}
```suggestion
function audon_addon_admin(string &$o)
{
	$t = Renderer::getMarkupTemplate('admin.tpl', 'addon/audon/');
	$o = Renderer::replaceMacros($t, [
		'$submit'   => DI::l10n()->t('Save Settings'),
		'$audonurl' => [
			'audonurl',
			DI::l10n()->t('audon Base URL'),
			DI::config()->get('audon','audonurl'),
			DI::l10n()->t('Page your users will create a audon Audio chat room on. For example you could use https://audon.space.'),
		],
	]);
}
```

2023-06-18 13:08 UTC, MrPetovan commented on audon/audon.php
> +}
```suggestion
function audon_addon_admin_post()
{
	DI::config()->set('audon', 'audonurl', trim($_POST['audonurl'] ?? ''));
}
```

2023-06-18 13:08 UTC, MrPetovan commented on audon/audon.php
> +	}
I changed the language which will require you to run `bin/run_xgettext.sh -a audon` from the base Friendica folder and commit the changes to `audon/lang/C/messages.po`.
```suggestion
	$o .= '<h2>' . DI::l10n()->t('Audio Chat') . '</h2>';
	$o .= '<p>' . DI::l10n()->t('Audon is an audio conferencing tool. Connect your account to Audon and create a room. Share the generated link to talk to other participants.') . '</p>';
	if ($audonurl == '') {
		$o .= '<p>' . DI::l10n()->t('Please contact your friendica administrator to remind them to configure the Audon addon.') . '</p>';
	} else {
		$o .= '<iframe src="' . $audonurl . '" width="740px" height="600px"></iframe>';
	}
```

2023-06-18 13:10 UTC, MrPetovan commented
Also, once you're done with your changes, you need to submit a PR to the Gitea repository: https://git.friendi.ca/friendica/friendica-addons

This repository is a read-only mirror of the official repository on Gitea.

2023-06-20 15:21 UTC, loma-one commented
Thank you very much for the proposed changes.

2023-06-20 15:21 UTC, closed without merging